name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.7'

    - name: Build Flutter web
      run: |
        flutter pub get
        flutter build web

    - name: Deploy to Azure VM
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        source: "build/web/*"
        target: "/var/www/frontend/"
